name: Dev1
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idenvironment
    environment: Dev1

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello - $secret1 - world!
        env:
          secret1: ${{ secrets.SECRET1 }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
